### ISSUE TITLE
Error message only on Android devices: Exception: type '_smi' is not a subtype of type 'string' in type cas

### ISSUE THREAD

**Issue by shaneonabike** [Teifun2/nextcloud-cookbook-flutter#114]
**Problem**

Recently, since the latest update, when viewing certain recipes I get this error message:
```Exception: type '_smi' is not a subtype of type 'string' in type cast```

**Reproduce**
1. Import the recipe https://www.thekitchn.com/how-to-make-meatballs-cooking-lessons-from-the-kitchn-108048#post-recipe-11231
2. View the recipe
3. Get the error message

**Versions**
Next cloud: 21.x
Cookbook Android App: Latest

Thanks for your awesome Android app. Something in the latest update is causing this issue, but I'm not sure what. Is there anyway that I can help you further to debug this?

**Comment by ruckb** [comment]
same issue with 
https://www.essen-und-trinken.de/rezepte/89843-rzpt-spinat-broccoli-nudelauflauf

I second shaneonabike comment about "thanks for the awesome Android app"    ;-) 
 
Hermann

**Comment by FrauNahtig** [comment]
Same issue here. I solved it by using a "sed-script" to format all json properties as strings.
Example:
- "width":187,"height":60 --> "width":"187","height":"60"

Apparently the app has some problems when casting integers.

**Comment by goebbe** [comment]
Same issue, here: 
Importing the following recipe via the Nextcloud Cookbook via the Nextcloud app (browser): 
https://www.essen-und-trinken.de/rezepte/54107-rzpt-kartoffelscheiben-aus-dem-ofen
Result: 
The recipe can be displayed/ edited via the Nextcloud-app (browser) - but not via the Nextcloud-cookbook-flutter. 
Instead, I receive the error message as described above. 

I can confirm that the problem seems to be related to the integers (as proposed by @FrauNahtig ):
Setting all integers in the recipe withing "" marks, manually, seems to solve the issue. 
from:
"ratingCount":219,"bestRating":5
to: 
"ratingCount":"219","bestRating":"5"

Please let me know, if I should upload the recipe.

**Comment by Teifun2** [comment]
Thanks for the indepth Analysis. Im sorry for my late response. I can reprodue it and will check if i am able to fix it. 

It seems that the newly added nutrition information is somtimes sent as Strings and sometimes sent as Integers and this is causing the issues.
