### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by rodude123** [Teifun2/nextcloud-cookbook-flutter#153]
so I recently updated my server, enabled 2fa and now I get `incorrect username and password` not sure what to do

**Comment by dagaz** [comment]
I have a similar Problem since the last App update:

Login is no longer possible. I did not enable 2FA. The login timeout takes forever. After killing the app I get a 404-error message if I restart it. The URL to my Nextcloud is correct and it is definitely not a network or firewall issue. My Nextcloud itself is reachable with the browser. Before the last app update it was issue #148.

Nextcloud Cookbook v. 0.7.7 (F-Droid)
Nexctloud v. 24.0.5
Cookbook v. 0.9.15
![Screenshot_20220923-102431_Nextcloud_Cookbook](https://user-images.githubusercontent.com/2174841/191920870-d3df2892-c0d6-4916-af8c-2ec873fe683e.png)

**Comment by sirdrakeistda** [comment]
Same issue here. I tried to reset the login credentials, but I still get the same error. I did not enable 2FA. It happened with the last update.

**Comment by Teifun2** [comment]
Please also check this: 
https://github.com/Teifun2/nextcloud-cookbook-flutter/issues/148#issuecomment-1252692620

Seems like it could help to recreate the app password.

**Comment by sirdrakeistda** [comment]
I tried to reinstall the app. Now I see the loading screen permanently. I can't even get to the login screen.

**Comment by sirdrakeistda** [comment]
> @sirdrakeistda Did you fully uninstall first? This is very weird behaviour scream
yes I fully uninstalled it. I tried the next version after. The new release (v. 0.7.8) seems to fix this issue. I hope it will be availeable in f-droid soon.
After the testing succesfully the github .apk I switched back to the f-droid version (to get updtes in the future). This resulted again in the loading loop.

Thanks for your great work.

**Comment by Teifun2** [comment]
I hope that all issues are resolved with 0.7.8 if this is not the case please open a new issue or reopen this one!
