### ISSUE TITLE
[Bug] Unable to login

### ISSUE THREAD

**Issue by lightlike** [Teifun2/nextcloud-cookbook-flutter#34]
**Information**
Nextcloud: 20 (Also happened on 19)
Nextcloud Cookbook: 0.7.7
Cookbook Android: 0.3.4

**Bug**
Unable to log in through different methods.

**Case 1**
1. Enter Url (with https, without https, the dav link and some other links)
2. Ender Username and Password (with 2FA enabled)
3. Error: Incorrect Username or Password

**Case 2**
1. Enter Url (with https, without https, the dav link and some other links)
2. Ender Username and Password (App-Password)
3. Error: 403 Forbidden

**Further Information**
- worked beforehand. Tried to login on other device, got error above. Tried relog on my device: see error above
- no errors shown in Nextcloud logs

**Comment by der-bender** [comment]
I've got the same issue with Nextcloud 20.0.4.

**Comment by Teifun2** [comment]
@lightlike 

Hello and thank you for reporting this issue! It seems to me to be the same problem mentioned in #13 
When i created the new update i did not think of 2FA which obviously was a mistake ^^

Currently its not possible to use your own created AppPassword and the app tries to create one himself. 

I will change this so that you can choose to provide your own AppPassword which should also allow the people with 2FA!

**Comment by der-bender** [comment]
Thanks a lot for your work!

**Comment by Teifun2** [comment]
@lightlike & @der-bender 

I implemented a fix and uploaded the new version as an APK here. The update on Google Play still needs to be reviewed before it will be rolled out. Could you check and give me feedback if this works now?

**Comment by lightlike** [comment]
Yup. 0.3.5 works like a charm.

**Comment by der-bender** [comment]
Also works in my setup - THANKS!
