### ISSUE TITLE
category load failed: firewall issue

### ISSUE THREAD

**Issue by winst0nsmith** [Teifun2/nextcloud-cookbook-flutter#52]
i get this error when running the app, as outlined in [#39](https://github.com/Teifun2/nextcloud-cookbook-flutter/issues/39). sorry to open a new issue, i don't know what the correct process is to re-open the closed one, or whatever. 

<code>Category Load Failed: Dio Error [DioErrorType.DEFAULT]: SocketException: OS Error: Connection refused, errno = 111, address = nextcloud.myserver.org, port = random-port-number</code>

i know there are other issues opened and closed regarding category load failures, but they are related to missing photos or files, and the clue to this one is right there in the error message: "Connection refused"

if i disable the firewall on my server the app works fine. i am guessing the app connects and authenticates via port 443, then wants to create a socket on one of the ephemeral ports (32768-65535) but fails. the firewall is configured to allow <code>established, related</code> so i don't see why this won't work.

thanks again for the hard work teifun2, the app looked great while i had my firewall down! lol. sorry it took me so long to get back here with more troubleshooting info.

-UPDATE-
ok the issue was with rate-limiting https connections on my firewall. not an issue with the app, unless it is slightly flooding the server. this is likely OT and please excuse me for raising the issue incorrectly if that is the case. once again, great app teifun2!

**Comment by Teifun2** [comment]
@winst0nsmith Thanks for investigating further. I already had someone else talking about a slight excess of HTTP connections that are used by the app. Currently i have no idea how to fix that because all the "requests" i do are done by high level libraries that do not allow me to reuse the same session for multiple requests.

I hope this is working fine for you now, and thanks for your kind words! 😄
