### ISSUE TITLE
Cannot login "HttpException: invalid header field name, with 59, ... "

### ISSUE THREAD

**Issue by benibunny** [Teifun2/nextcloud-cookbook-flutter#54]
I have nextcloud and cookbook installed on synology. Cookbook works fine, but I can't login with the app. 

The error message is 

DioError [DioErrorType.DEFAULT]: HttpException: Invalid header field name, with 59, uri = https://10.0.0.6/nextcloud/ocs/v2.php/core/getapppassword

nextcloud version is 20.0.8
cookbook version is 0.8.4
app version is 0.4.0

What can I do to debug this issue further?

![Screenshot_2021-03-13-22-19-25-272_com nextcloud_cookbook_flutter1](https://user-images.githubusercontent.com/6209862/111151571-eabcee80-858f-11eb-8a70-18e2242b0f39.jpg)

**Comment by Teifun2** [comment]
Hello

I'm sorry to hear that the app is not able to connect to your local setup.
Sadly i'm not able to reproduce this behavior on my own local setup, but its not exactly the same obviously.

To me it seems that the app does not understand which part of the URL is host portion and which is path portion.

Things i would suggest that you could try:
- Import the attached postman config and run it from your device to check if it works properly. (You need to fill in the Basic Auth details)
[export.postman_collection.zip](https://github.com/Teifun2/nextcloud-cookbook-flutter/files/6175672/export.postman_collection.zip)

- Setup nextcloud on a specific port so that the adress is 10.0.0.6:8080 (or wathever you want)
- Try the above suggestion with and without /nextcloud (Server settings need to be changed for this :S)

If i can help you anyhow to debug this let me know!

**Comment by Kage1** [comment]
Try creating a New App Password in Nextcloud under Security - Devices & sessions. Then check the top box in the dialog.

**Comment by Teifun2** [comment]
I will close this now as i cannot reproduce this issue and have not heard back from the creator of the issue.
