### ISSUE TITLE
Adding checkboxes for ingredients

### ISSUE THREAD

**Issue by shaneonabike** [Teifun2/nextcloud-cookbook-flutter#66]
**Is your feature request related to a problem? Please describe.**
I came across this article, which I found it really interesting to engage for more (long term) changes that could be considered for cookbook. Seriously though I really love this extension it is amazing!

Ref: https://www.simeongriggs.dev/designing-a-more-complete-recipe-website

**Describe the solution you'd like**

- [ ] Checkbox on ingredients (this one is already there on the steps but I would love that for ingredients)
-  Conversion tool (from grams to ounce)

Note: I realize probably that the conversion tool might be a stretch but I think a checkbox for ingredients would be amazing! I get distributed sometimes with my kids so it's hard to remember where I left off :P

**Comment by Teifun2** [comment]
First of all thanks for your kind feedback.

To your suggestions

Conversion Tool:
This will sadly not happen as long as the web app itself does not have a way to handle this,
I did see your issue 704 on the main cookbook repo were you where referenced to
https://github.com/nextcloud/cookbook/issues/116

This would also be the best point to drive this topic, altough it is a very hard one for the setup that was chosen!

Checkbox on Ingredients:
This is a very good idea. The thing is i'm not sure how i would do this "with the limited" screenspace but without being fiddly.
If i would do it similar to the implementation on the web i see many "missklicks" incoming. On the other hand the big round circles take way to much space for each element of an ingredient list.

What is your opinion? A doodle of an idea would be much appreciated because it helps me to envision how it should look!

PS: I rename the issue so we can track it for the ingredients checkbox. If the conversion works in web we can open a new issue for this.

**Comment by dugite-code** [comment]
Is the limited screen space really that much of an issue? The instruction list doesn't feel too crowded and a simple checkbox would be smaller with the horizontal space. Vertically the ingredient list is already collapsible and it is at the end of the day a vertical list making scrolling through intuitive.

You could always try something similar the the shopping list integration in home assistant and drop checked items down into a separate checked items list. That way you could move through the list without having to scroll, additionally you could make the Checked items list collapsible to hide it away when reading the instructions.

![image](https://user-images.githubusercontent.com/12742064/130001027-226e2b89-5bd8-4e58-baa1-05e264a20802.png)

Another potential option is to make the whole ingredient row clickable and simply change the background colour

![image](https://user-images.githubusercontent.com/12742064/130001988-c1567efc-990c-4a9b-b52c-d1877d940450.png)
