### ISSUE TITLE
Version 0.8 not working on Huawei MatePad T (AGS3-W09)

### ISSUE THREAD

**Issue by OleAlbers** [Teifun2/nextcloud-cookbook-flutter#94]
On the MatePad Version 0.7.0 is not working correctly. When starting the app just a white blank page appears and nothing else happens.

When downgrading to the previous version 0.6.0 everything is fine.

This tablet has no Google Play Services installed which might or might not  be something that could lead to the problem.

I am happy to provide any logfiles if needed

(LOW priority as I can still work and don't want to ruin your holidays :) )

**Comment by OleAlbers** [comment]
Tried to log the error but suddenly everything worked after connecting through adb. Not really sure what to think about this as I was able to reproduce the error even through multiple reboots before but it is gone notetheless.

**Comment by Teifun2** [comment]
@OleAlbers Hmm this is interesting.

Did you ever completelty uninstall and then install the app when you had the issue? (or just replaced it with different versions?)

It is possible that the local store of the settings was somehow corrupted, and could no be read from 0.7.  

However i would not know why this woul be fixed by adb connection :D
